// eslint-disable-next-line no-unused-expressions
const topTenFoodsList = [
    {
      "food": {
        "brand_name": "Snickers",
        "food_id": "5868541",
        "food_name": "Snickers Bar (1.86 oz)",
        "food_type": "Brand",
        "food_url": "https://www.fatsecret.com/calories-nutrition/snickers/snickers-bar-(186-oz)",
        "servings": {
          "serving": {
            "calcium": "4",
            "calories": "250",
            "carbohydrate": "33",
            "cholesterol": "5",
            "fat": "12",
            "fiber": "1",
            "iron": "2",
            "measurement_description": "serving",
            "metric_serving_amount": "1.860",
            "metric_serving_unit": "oz",
            "number_of_units": "1.000",
            "protein": "4",
            "saturated_fat": "4.5",
            "serving_description": "1 bar",
            "serving_id": "5695412",
            "serving_url": "https://www.fatsecret.com/calories-nutrition/snickers/snickers-bar-(186-oz)",
            "sodium": "120",
            "sugar": "27",
            "trans_fat": "0",
            "vitamin_a": "0",
            "vitamin_c": "0"
          }
        }
      }
    },
    {
      "food": {
        "food_id": "546030",
        "food_name": "Beef Meatballs",
        "food_type": "Generic",
        "food_url": "https://www.fatsecret.com/calories-nutrition/generic/meatballs-beef",
        "servings": {
          "serving": [
            {
              "calcium": "0",
              "calories": "14",
              "carbohydrate": "0.53",
              "cholesterol": "5",
              "fat": "0.92",
              "fiber": "0",
              "iron": "1",
              "measurement_description": "cocktail",
              "metric_serving_amount": "7.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.393",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.041",
              "potassium": "15",
              "protein": "0.87",
              "saturated_fat": "0.348",
              "serving_description": "1 cocktail",
              "serving_id": "570238",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/meatballs-beef?portionid=570238&portionamount=1.000",
              "sodium": "33",
              "sugar": "0.11",
              "trans_fat": "0.051",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "1",
              "calories": "28",
              "carbohydrate": "1.06",
              "cholesterol": "10",
              "fat": "1.84",
              "fiber": "0.1",
              "iron": "1",
              "measurement_description": "small",
              "metric_serving_amount": "14.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.785",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.081",
              "potassium": "30",
              "protein": "1.74",
              "saturated_fat": "0.697",
              "serving_description": "1 small",
              "serving_id": "570239",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/meatballs-beef?portionid=570239&portionamount=1.000",
              "sodium": "67",
              "sugar": "0.21",
              "trans_fat": "0.102",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "1",
              "calories": "57",
              "carbohydrate": "2.12",
              "cholesterol": "21",
              "fat": "3.69",
              "fiber": "0.1",
              "iron": "3",
              "measurement_description": "medium",
              "metric_serving_amount": "28.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.570",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.163",
              "potassium": "60",
              "protein": "3.47",
              "saturated_fat": "1.394",
              "serving_description": "1 medium",
              "serving_id": "570240",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/meatballs-beef?portionid=570240&portionamount=1.000",
              "sodium": "134",
              "sugar": "0.42",
              "trans_fat": "0.205",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "2",
              "calories": "85",
              "carbohydrate": "3.18",
              "cholesterol": "31",
              "fat": "5.53",
              "fiber": "0.2",
              "iron": "4",
              "measurement_description": "large",
              "metric_serving_amount": "42.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "2.355",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.244",
              "potassium": "89",
              "protein": "5.21",
              "saturated_fat": "2.091",
              "serving_description": "1 large",
              "serving_id": "570241",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/meatballs-beef?portionid=570241&portionamount=1.000",
              "sodium": "201",
              "sugar": "0.64",
              "trans_fat": "0.307",
              "vitamin_a": "0",
              "vitamin_c": "1"
            },
            {
              "calcium": "6",
              "calories": "283",
              "carbohydrate": "10.61",
              "cholesterol": "104",
              "fat": "18.43",
              "fiber": "0.6",
              "iron": "14",
              "measurement_description": "cup",
              "metric_serving_amount": "140.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "7.850",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.814",
              "potassium": "298",
              "protein": "17.37",
              "saturated_fat": "6.969",
              "serving_description": "1 cup",
              "serving_id": "570245",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/meatballs-beef?portionid=570245&portionamount=1.000",
              "sodium": "669",
              "sugar": "2.12",
              "trans_fat": "1.023",
              "vitamin_a": "1",
              "vitamin_c": "2"
            },
            {
              "calcium": "1",
              "calories": "38",
              "carbohydrate": "1.44",
              "cholesterol": "14",
              "fat": "2.50",
              "fiber": "0.1",
              "iron": "2",
              "measurement_description": "cubic inch",
              "metric_serving_amount": "19.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.065",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.111",
              "potassium": "40",
              "protein": "2.36",
              "saturated_fat": "0.946",
              "serving_description": "1 cubic inch",
              "serving_id": "570246",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/meatballs-beef?portionid=570246&portionamount=1.000",
              "sodium": "91",
              "sugar": "0.29",
              "trans_fat": "0.139",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "1",
              "calories": "57",
              "carbohydrate": "2.15",
              "cholesterol": "21",
              "fat": "3.73",
              "fiber": "0.1",
              "iron": "3",
              "measurement_description": "oz",
              "metric_serving_amount": "28.350",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.590",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.165",
              "potassium": "60",
              "protein": "3.52",
              "saturated_fat": "1.411",
              "serving_description": "1 oz",
              "serving_id": "570247",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/meatballs-beef?portionid=570247&portionamount=1.000",
              "sodium": "135",
              "sugar": "0.43",
              "trans_fat": "0.207",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "5",
              "calories": "218",
              "carbohydrate": "8.18",
              "cholesterol": "80",
              "fat": "14.22",
              "fiber": "0.5",
              "iron": "11",
              "measurement_description": "serving (108g)",
              "metric_serving_amount": "108.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "6.056",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.628",
              "potassium": "230",
              "protein": "13.40",
              "saturated_fat": "5.376",
              "serving_description": "1 serving (108 g)",
              "serving_id": "570248",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/meatballs-beef?portionid=570248&portionamount=1.000",
              "sodium": "516",
              "sugar": "1.63",
              "trans_fat": "0.789",
              "vitamin_a": "1",
              "vitamin_c": "1"
            },
            {
              "calcium": "1",
              "calories": "44",
              "carbohydrate": "1.67",
              "cholesterol": "16",
              "fat": "2.90",
              "fiber": "0.1",
              "iron": "2",
              "measurement_description": "oz, raw (yield after cooking)",
              "metric_serving_amount": "22.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.234",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.128",
              "potassium": "47",
              "protein": "2.73",
              "saturated_fat": "1.095",
              "serving_description": "1 oz raw (yield after cooking)",
              "serving_id": "570249",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/meatballs-beef?portionid=570249&portionamount=1.000",
              "sodium": "105",
              "sugar": "0.33",
              "trans_fat": "0.161",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "5",
              "calories": "202",
              "carbohydrate": "7.58",
              "cholesterol": "74",
              "fat": "13.16",
              "fiber": "0.5",
              "iron": "10",
              "measurement_description": "g",
              "metric_serving_amount": "100.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "5.607",
              "number_of_units": "100.000",
              "polyunsaturated_fat": "0.582",
              "potassium": "213",
              "protein": "12.41",
              "saturated_fat": "4.978",
              "serving_description": "100 g",
              "serving_id": "570250",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/meatballs-beef?portionid=570250&portionamount=100.000",
              "sodium": "478",
              "sugar": "1.51",
              "trans_fat": "0.731",
              "vitamin_a": "1",
              "vitamin_c": "1"
            }
          ]
        }
      }
    },
    {
      "food": {
        "food_id": "1713",
        "food_name": "Chicken Wing",
        "food_type": "Generic",
        "food_url": "https://www.fatsecret.com/calories-nutrition/generic/chicken-wing-ns-as-to-skin-eaten",
        "servings": {
          "serving": [
            {
              "calcium": "0",
              "calories": "81",
              "carbohydrate": "0",
              "cholesterol": "23",
              "fat": "5.40",
              "fiber": "0",
              "iron": "2",
              "measurement_description": "small wing (yield after cooking, bone removed)",
              "metric_serving_amount": "28.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "2.121",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "1.150",
              "potassium": "51",
              "protein": "7.46",
              "saturated_fat": "1.513",
              "serving_description": "1 small (yield after cooking, bone removed)",
              "serving_id": "6256",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/chicken-wing-ns-as-to-skin-eaten?portionid=6256&portionamount=1.000",
              "sodium": "113",
              "sugar": "0",
              "vitamin_a": "1",
              "vitamin_c": "0"
            },
            {
              "calcium": "0",
              "calories": "92",
              "carbohydrate": "0",
              "cholesterol": "27",
              "fat": "6.18",
              "fiber": "0",
              "iron": "2",
              "measurement_description": "medium wing (yield after cooking, bone removed)",
              "metric_serving_amount": "32.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "2.424",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "1.314",
              "potassium": "59",
              "protein": "8.52",
              "saturated_fat": "1.729",
              "serving_description": "1 medium (yield after cooking, bone removed)",
              "serving_id": "6258",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/chicken-wing-ns-as-to-skin-eaten?portionid=6258&portionamount=1.000",
              "sodium": "129",
              "sugar": "0",
              "vitamin_a": "1",
              "vitamin_c": "0"
            },
            {
              "calcium": "1",
              "calories": "124",
              "carbohydrate": "0",
              "cholesterol": "36",
              "fat": "8.30",
              "fiber": "0",
              "iron": "3",
              "measurement_description": "large wing (yield after cooking, bone removed)",
              "metric_serving_amount": "43.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "3.258",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "1.765",
              "potassium": "79",
              "protein": "11.46",
              "saturated_fat": "2.324",
              "serving_description": "1 large (yield after cooking, bone removed)",
              "serving_id": "5825",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/chicken-wing-ns-as-to-skin-eaten?portionid=5825&portionamount=1.000",
              "sodium": "174",
              "sugar": "0",
              "vitamin_a": "1",
              "vitamin_c": "0"
            },
            {
              "calcium": "0",
              "calories": "43",
              "carbohydrate": "0",
              "cholesterol": "12",
              "fat": "2.89",
              "fiber": "0",
              "iron": "1",
              "measurement_description": "oz, with bone, cooked (yield after bone removed)",
              "metric_serving_amount": "15.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.136",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.616",
              "potassium": "27",
              "protein": "4.00",
              "saturated_fat": "0.811",
              "serving_description": "1 oz, with bone cooked (yield after bone removed)",
              "serving_id": "6260",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/chicken-wing-ns-as-to-skin-eaten?portionid=6260&portionamount=1.000",
              "sodium": "61",
              "sugar": "0",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "0",
              "calories": "29",
              "carbohydrate": "0",
              "cholesterol": "8",
              "fat": "1.93",
              "fiber": "0",
              "iron": "1",
              "measurement_description": "oz, with bone, raw (yield after cooking, bone removed)",
              "metric_serving_amount": "10.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.758",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.411",
              "potassium": "18",
              "protein": "2.66",
              "saturated_fat": "0.540",
              "serving_description": "1 oz, with bone (yield after cooking, bone removed)",
              "serving_id": "6262",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/chicken-wing-ns-as-to-skin-eaten?portionid=6262&portionamount=1.000",
              "sodium": "40",
              "sugar": "0",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "0",
              "calories": "92",
              "carbohydrate": "0",
              "cholesterol": "27",
              "fat": "6.18",
              "fiber": "0",
              "iron": "2",
              "measurement_description": "serving (32g)",
              "metric_serving_amount": "32.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "2.424",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "1.314",
              "potassium": "59",
              "protein": "8.52",
              "saturated_fat": "1.729",
              "serving_description": "1 serving (32 g)",
              "serving_id": "6264",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/chicken-wing-ns-as-to-skin-eaten?portionid=6264&portionamount=1.000",
              "sodium": "129",
              "sugar": "0",
              "vitamin_a": "1",
              "vitamin_c": "0"
            },
            {
              "calcium": "0",
              "calories": "55",
              "carbohydrate": "0",
              "cholesterol": "16",
              "fat": "3.67",
              "fiber": "0",
              "iron": "1",
              "measurement_description": "\"drummette\" (mini drumstick from a wing)",
              "metric_serving_amount": "19.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.440",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.780",
              "potassium": "35",
              "protein": "5.06",
              "saturated_fat": "1.027",
              "serving_description": "1 \"drummette\" (mini drumstick from a wing)",
              "serving_id": "6267",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/chicken-wing-ns-as-to-skin-eaten?portionid=6267&portionamount=1.000",
              "sodium": "77",
              "sugar": "0",
              "vitamin_a": "1",
              "vitamin_c": "0"
            },
            {
              "calcium": "2",
              "calories": "288",
              "carbohydrate": "0",
              "cholesterol": "83",
              "fat": "19.30",
              "fiber": "0",
              "iron": "7",
              "measurement_description": "g",
              "metric_serving_amount": "100.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "7.576",
              "number_of_units": "100.000",
              "polyunsaturated_fat": "4.106",
              "potassium": "183",
              "protein": "26.64",
              "saturated_fat": "5.405",
              "serving_description": "100 g",
              "serving_id": "50393",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/chicken-wing-ns-as-to-skin-eaten?portionid=50393&portionamount=100.000",
              "sodium": "404",
              "sugar": "0",
              "vitamin_a": "3",
              "vitamin_c": "0"
            }
          ]
        }
      }
    },
    {
      "food": {
        "food_id": "4424",
        "food_name": "Spaghetti",
        "food_type": "Generic",
        "food_url": "https://www.fatsecret.com/calories-nutrition/generic/spaghetti-cooked",
        "servings": {
          "serving": [
            {
              "calcium": "1",
              "calories": "220",
              "carbohydrate": "42.95",
              "cholesterol": "0",
              "fat": "1.29",
              "fiber": "2.5",
              "iron": "10",
              "measurement_description": "cup, cooked",
              "metric_serving_amount": "140.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.182",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.444",
              "potassium": "63",
              "protein": "8.06",
              "saturated_fat": "0.245",
              "serving_description": "1 cup cooked",
              "serving_id": "15834",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/spaghetti-cooked?portionid=15834&portionamount=1.000",
              "sodium": "325",
              "sugar": "0.78",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "1",
              "calories": "126",
              "carbohydrate": "24.54",
              "cholesterol": "0",
              "fat": "0.74",
              "fiber": "1.4",
              "iron": "6",
              "measurement_description": "oz, dry, yields",
              "metric_serving_amount": "80.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.104",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.254",
              "potassium": "36",
              "protein": "4.61",
              "saturated_fat": "0.140",
              "serving_description": "1 oz, dry, yields",
              "serving_id": "16289",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/spaghetti-cooked?portionid=16289&portionamount=1.000",
              "sodium": "186",
              "sugar": "0.45",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "1",
              "calories": "220",
              "carbohydrate": "42.95",
              "cholesterol": "0",
              "fat": "1.29",
              "fiber": "2.5",
              "iron": "10",
              "measurement_description": "serving (140g)",
              "metric_serving_amount": "140.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.182",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.444",
              "potassium": "63",
              "protein": "8.06",
              "saturated_fat": "0.245",
              "serving_description": "1 serving (140 g)",
              "serving_id": "14860",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/spaghetti-cooked?portionid=14860&portionamount=1.000",
              "sodium": "325",
              "sugar": "0.78",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "1",
              "calories": "157",
              "carbohydrate": "30.68",
              "cholesterol": "0",
              "fat": "0.92",
              "fiber": "1.8",
              "iron": "7",
              "measurement_description": "g",
              "metric_serving_amount": "100.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.130",
              "number_of_units": "100.000",
              "polyunsaturated_fat": "0.317",
              "potassium": "45",
              "protein": "5.76",
              "saturated_fat": "0.175",
              "serving_description": "100 g",
              "serving_id": "53104",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/spaghetti-cooked?portionid=53104&portionamount=100.000",
              "sodium": "232",
              "sugar": "0.56",
              "vitamin_a": "0",
              "vitamin_c": "0"
            }
          ]
        }
      }
    },
    {
      "food": {
        "food_id": "39926",
        "food_name": "Cheeseburger",
        "food_type": "Generic",
        "food_url": "https://www.fatsecret.com/calories-nutrition/usda/cheeseburger",
        "servings": {
          "serving": [
            {
              "calcium": "14",
              "calories": "319",
              "carbohydrate": "31.75",
              "cholesterol": "50",
              "fat": "15.15",
              "iron": "14",
              "measurement_description": "sandwich",
              "metric_serving_amount": "102.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "5.773",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "1.540",
              "potassium": "164",
              "protein": "14.77",
              "saturated_fat": "6.467",
              "serving_description": "1 sandwich",
              "serving_id": "40534",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/usda/cheeseburger?portionid=40534&portionamount=1.000",
              "sodium": "500",
              "vitamin_a": "3",
              "vitamin_c": "0"
            },
            {
              "calcium": "4",
              "calories": "89",
              "carbohydrate": "8.83",
              "cholesterol": "14",
              "fat": "4.21",
              "iron": "4",
              "measurement_description": "oz",
              "metric_serving_amount": "28.350",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.605",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.428",
              "potassium": "46",
              "protein": "4.11",
              "saturated_fat": "1.797",
              "serving_description": "1 oz",
              "serving_id": "46104",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/usda/cheeseburger?portionid=46104&portionamount=1.000",
              "sodium": "139",
              "vitamin_a": "1",
              "vitamin_c": "0"
            },
            {
              "calcium": "14",
              "calories": "313",
              "carbohydrate": "31.13",
              "cholesterol": "49",
              "fat": "14.85",
              "iron": "13",
              "measurement_description": "g",
              "metric_serving_amount": "100.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "5.660",
              "number_of_units": "100.000",
              "polyunsaturated_fat": "1.510",
              "potassium": "161",
              "protein": "14.48",
              "saturated_fat": "6.340",
              "serving_description": "100 g",
              "serving_id": "62657",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/usda/cheeseburger?portionid=62657&portionamount=100.000",
              "sodium": "490",
              "vitamin_a": "3",
              "vitamin_c": "0"
            }
          ]
        }
      }
    },
    {
      "food": {
        "food_id": "1385",
        "food_name": "Roast Beef",
        "food_type": "Generic",
        "food_url": "https://www.fatsecret.com/calories-nutrition/generic/beef-roast-roasted",
        "servings": {
          "serving": [
            {
              "calcium": "0",
              "calories": "56",
              "carbohydrate": "0",
              "cholesterol": "16",
              "fat": "3.64",
              "fiber": "0",
              "iron": "3",
              "measurement_description": "thin slice (approx 4-1/2\" x 2-1/2\" x 1/8\")",
              "metric_serving_amount": "21.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.545",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.132",
              "potassium": "61",
              "protein": "5.44",
              "saturated_fat": "1.431",
              "serving_description": "1 thin slice (approx 4-1/2\" x 2-1/2\" x 1/8\")",
              "serving_id": "1616",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/beef-roast-roasted?portionid=1616&portionamount=1.000",
              "sodium": "46",
              "sugar": "0",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "0",
              "calories": "112",
              "carbohydrate": "0",
              "cholesterol": "32",
              "fat": "7.27",
              "fiber": "0",
              "iron": "6",
              "measurement_description": "medium slice (approx 4-1/2\" x 2-1/2\" x 1/4\")",
              "metric_serving_amount": "42.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "3.089",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.263",
              "potassium": "123",
              "protein": "10.88",
              "saturated_fat": "2.862",
              "serving_description": "1 medium slice (approx 4-1/2\" x 2-1/2\" x 1/4\")",
              "serving_id": "1618",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/beef-roast-roasted?portionid=1618&portionamount=1.000",
              "sodium": "91",
              "sugar": "0",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "1",
              "calories": "168",
              "carbohydrate": "0",
              "cholesterol": "48",
              "fat": "10.91",
              "fiber": "0",
              "iron": "9",
              "measurement_description": "thick slice (approx 4-1/2\" x 2-1/2\" x 3/8\")",
              "metric_serving_amount": "63.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "4.634",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.395",
              "potassium": "184",
              "protein": "16.32",
              "saturated_fat": "4.292",
              "serving_description": "1 thick slice (approx 4-1/2\" x 2-1/2\" x 3/8\")",
              "serving_id": "1619",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/beef-roast-roasted?portionid=1619&portionamount=1.000",
              "sodium": "137",
              "sugar": "0",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "0",
              "calories": "59",
              "carbohydrate": "0",
              "cholesterol": "17",
              "fat": "3.81",
              "fiber": "0",
              "iron": "3",
              "measurement_description": "oz, with bone, cooked (yield after bone removed)",
              "metric_serving_amount": "22.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.618",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.138",
              "potassium": "64",
              "protein": "5.70",
              "saturated_fat": "1.499",
              "serving_description": "1 oz, with bone (yield after bone removed)",
              "serving_id": "2020",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/beef-roast-roasted?portionid=2020&portionamount=1.000",
              "sodium": "48",
              "sugar": "0",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "0",
              "calories": "45",
              "carbohydrate": "0",
              "cholesterol": "13",
              "fat": "2.94",
              "fiber": "0",
              "iron": "2",
              "measurement_description": "oz, with bone, raw (yield after cooking, bone removed)",
              "metric_serving_amount": "17.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.250",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.107",
              "potassium": "50",
              "protein": "4.40",
              "saturated_fat": "1.158",
              "serving_description": "1 oz, with bone (yield after cooking, bone removed)",
              "serving_id": "2021",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/beef-roast-roasted?portionid=2021&portionamount=1.000",
              "sodium": "37",
              "sugar": "0",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "0",
              "calories": "76",
              "carbohydrate": "0",
              "cholesterol": "22",
              "fat": "4.91",
              "fiber": "0",
              "iron": "4",
              "measurement_description": "oz, boneless, cooked",
              "metric_serving_amount": "28.350",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "2.085",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.178",
              "potassium": "83",
              "protein": "7.35",
              "saturated_fat": "1.932",
              "serving_description": "1 oz boneless",
              "serving_id": "1620",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/beef-roast-roasted?portionid=1620&portionamount=1.000",
              "sodium": "62",
              "sugar": "0",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "0",
              "calories": "59",
              "carbohydrate": "0",
              "cholesterol": "17",
              "fat": "3.81",
              "fiber": "0",
              "iron": "3",
              "measurement_description": "oz, boneless, raw (yield after cooking)",
              "metric_serving_amount": "22.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.618",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.138",
              "potassium": "64",
              "protein": "5.70",
              "saturated_fat": "1.499",
              "serving_description": "1 oz boneless (yield after cooking)",
              "serving_id": "2022",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/beef-roast-roasted?portionid=2022&portionamount=1.000",
              "sodium": "48",
              "sugar": "0",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "0",
              "calories": "45",
              "carbohydrate": "0",
              "cholesterol": "13",
              "fat": "2.94",
              "fiber": "0",
              "iron": "2",
              "measurement_description": "cubic inch, boneless, cooked",
              "metric_serving_amount": "17.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.250",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.107",
              "potassium": "50",
              "protein": "4.40",
              "saturated_fat": "1.158",
              "serving_description": "1 cubic inch boneless",
              "serving_id": "2023",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/beef-roast-roasted?portionid=2023&portionamount=1.000",
              "sodium": "37",
              "sugar": "0",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "1",
              "calories": "358",
              "carbohydrate": "0",
              "cholesterol": "102",
              "fat": "23.21",
              "fiber": "0",
              "iron": "18",
              "measurement_description": "cup, cooked, diced",
              "metric_serving_amount": "134.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "9.856",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.841",
              "potassium": "391",
              "protein": "34.72",
              "saturated_fat": "9.130",
              "serving_description": "1 cup diced",
              "serving_id": "1622",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/beef-roast-roasted?portionid=1622&portionamount=1.000",
              "sodium": "291",
              "sugar": "0",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "1",
              "calories": "227",
              "carbohydrate": "0",
              "cholesterol": "65",
              "fat": "14.72",
              "fiber": "0",
              "iron": "12",
              "measurement_description": "serving (85g)",
              "metric_serving_amount": "85.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "6.252",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.533",
              "potassium": "248",
              "protein": "22.02",
              "saturated_fat": "5.791",
              "serving_description": "1 serving (85 g)",
              "serving_id": "2024",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/beef-roast-roasted?portionid=2024&portionamount=1.000",
              "sodium": "184",
              "sugar": "0",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "1",
              "calories": "267",
              "carbohydrate": "0",
              "cholesterol": "76",
              "fat": "17.32",
              "fiber": "0",
              "iron": "14",
              "measurement_description": "g",
              "metric_serving_amount": "100.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "7.355",
              "number_of_units": "100.000",
              "polyunsaturated_fat": "0.627",
              "potassium": "292",
              "protein": "25.91",
              "saturated_fat": "6.813",
              "serving_description": "100 g",
              "serving_id": "50065",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/beef-roast-roasted?portionid=50065&portionamount=100.000",
              "sodium": "217",
              "sugar": "0",
              "vitamin_a": "0",
              "vitamin_c": "0"
            }
          ]
        }
      }
    },
    {
      "food": {
        "food_id": "2057",
        "food_name": "Salmon",
        "food_type": "Generic",
        "food_url": "https://www.fatsecret.com/calories-nutrition/generic/salmon-raw",
        "servings": {
          "serving": [
            {
              "calcium": "1",
              "calories": "41",
              "carbohydrate": "0",
              "cholesterol": "13",
              "fat": "1.68",
              "fiber": "0",
              "iron": "1",
              "measurement_description": "oz, boneless, raw",
              "metric_serving_amount": "28.350",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.605",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.565",
              "potassium": "120",
              "protein": "6.13",
              "saturated_fat": "0.357",
              "serving_description": "1 oz boneless",
              "serving_id": "8653",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/salmon-raw?portionid=8653&portionamount=1.000",
              "sodium": "13",
              "sugar": "0",
              "vitamin_a": "1",
              "vitamin_c": "0"
            },
            {
              "calcium": "6",
              "calories": "242",
              "carbohydrate": "0",
              "cholesterol": "75",
              "fat": "9.84",
              "fiber": "0",
              "iron": "5",
              "measurement_description": "cup, NFS",
              "metric_serving_amount": "166.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "3.542",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "3.307",
              "potassium": "702",
              "protein": "35.89",
              "saturated_fat": "2.092",
              "serving_description": "1 cup, NFS",
              "serving_id": "6814",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/salmon-raw?portionid=6814&portionamount=1.000",
              "sodium": "76",
              "sugar": "0",
              "vitamin_a": "3",
              "vitamin_c": "3"
            },
            {
              "calcium": "2",
              "calories": "83",
              "carbohydrate": "0",
              "cholesterol": "26",
              "fat": "3.38",
              "fiber": "0",
              "iron": "2",
              "measurement_description": "serving (57g)",
              "metric_serving_amount": "57.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.216",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "1.135",
              "potassium": "241",
              "protein": "12.32",
              "saturated_fat": "0.718",
              "serving_description": "1 serving (57 g)",
              "serving_id": "7415",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/salmon-raw?portionid=7415&portionamount=1.000",
              "sodium": "26",
              "sugar": "0",
              "vitamin_a": "1",
              "vitamin_c": "1"
            },
            {
              "calcium": "4",
              "calories": "146",
              "carbohydrate": "0",
              "cholesterol": "45",
              "fat": "5.93",
              "fiber": "0",
              "iron": "3",
              "measurement_description": "g",
              "metric_serving_amount": "100.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "2.134",
              "number_of_units": "100.000",
              "polyunsaturated_fat": "1.992",
              "potassium": "423",
              "protein": "21.62",
              "saturated_fat": "1.260",
              "serving_description": "100 g",
              "serving_id": "50737",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/salmon-raw?portionid=50737&portionamount=100.000",
              "sodium": "46",
              "sugar": "0",
              "vitamin_a": "2",
              "vitamin_c": "2"
            }
          ]
        }
      }
    },
    {
      "food": {
        "food_id": "1972",
        "food_name": "Fried Battered Cod",
        "food_type": "Generic",
        "food_url": "https://www.fatsecret.com/calories-nutrition/generic/cod-battered-fried",
        "servings": {
          "serving": [
            {
              "calcium": "1",
              "calories": "47",
              "carbohydrate": "1.87",
              "cholesterol": "14",
              "fat": "2.16",
              "fiber": "0.1",
              "iron": "1",
              "measurement_description": "oz, boneless, raw (yield after cooking)",
              "metric_serving_amount": "27.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.940",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.603",
              "potassium": "103",
              "protein": "4.71",
              "saturated_fat": "0.450",
              "serving_description": "1 oz boneless (yield after cooking)",
              "serving_id": "7335",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/cod-battered-fried?portionid=7335&portionamount=1.000",
              "sodium": "34",
              "sugar": "0.11",
              "vitamin_a": "0",
              "vitamin_c": "1"
            },
            {
              "calcium": "1",
              "calories": "49",
              "carbohydrate": "1.97",
              "cholesterol": "14",
              "fat": "2.27",
              "fiber": "0.1",
              "iron": "1",
              "measurement_description": "oz, boneless, cooked",
              "metric_serving_amount": "28.350",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.987",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.633",
              "potassium": "109",
              "protein": "4.94",
              "saturated_fat": "0.473",
              "serving_description": "1 oz boneless",
              "serving_id": "7994",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/cod-battered-fried?portionid=7994&portionamount=1.000",
              "sodium": "35",
              "sugar": "0.12",
              "vitamin_a": "0",
              "vitamin_c": "1"
            },
            {
              "calcium": "1",
              "calories": "31",
              "carbohydrate": "1.25",
              "cholesterol": "9",
              "fat": "1.44",
              "fiber": "0",
              "iron": "1",
              "measurement_description": "oz, with bone, raw (yield after cooking, bone removed)",
              "metric_serving_amount": "18.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.627",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.402",
              "potassium": "69",
              "protein": "3.14",
              "saturated_fat": "0.300",
              "serving_description": "1 oz, with bone (yield after cooking, bone removed)",
              "serving_id": "7336",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/cod-battered-fried?portionid=7336&portionamount=1.000",
              "sodium": "23",
              "sugar": "0.08",
              "vitamin_a": "0",
              "vitamin_c": "1"
            },
            {
              "calcium": "1",
              "calories": "33",
              "carbohydrate": "1.32",
              "cholesterol": "10",
              "fat": "1.52",
              "fiber": "0",
              "iron": "1",
              "measurement_description": "oz, with bone, cooked (yield after bone removed)",
              "metric_serving_amount": "19.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.662",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.424",
              "potassium": "73",
              "protein": "3.31",
              "saturated_fat": "0.317",
              "serving_description": "1 oz, with bone (yield after bone removed)",
              "serving_id": "8311",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/cod-battered-fried?portionid=8311&portionamount=1.000",
              "sodium": "24",
              "sugar": "0.08",
              "vitamin_a": "0",
              "vitamin_c": "1"
            },
            {
              "calcium": "0",
              "calories": "19",
              "carbohydrate": "0.76",
              "cholesterol": "5",
              "fat": "0.88",
              "fiber": "0",
              "iron": "0",
              "measurement_description": "cubic inch, with bone, cooked (yield after bone removed)",
              "metric_serving_amount": "11.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.383",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.246",
              "potassium": "42",
              "protein": "1.92",
              "saturated_fat": "0.183",
              "serving_description": "1 cubic inch, with bone (yield after bone removed)",
              "serving_id": "7145",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/cod-battered-fried?portionid=7145&portionamount=1.000",
              "sodium": "14",
              "sugar": "0.05",
              "vitamin_a": "0",
              "vitamin_c": "0"
            },
            {
              "calcium": "0",
              "calories": "29",
              "carbohydrate": "1.18",
              "cholesterol": "9",
              "fat": "1.36",
              "fiber": "0",
              "iron": "1",
              "measurement_description": "cubic inch, boneless, cooked",
              "metric_serving_amount": "17.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "0.592",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.380",
              "potassium": "65",
              "protein": "2.96",
              "saturated_fat": "0.283",
              "serving_description": "1 cubic inch boneless",
              "serving_id": "8231",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/cod-battered-fried?portionid=8231&portionamount=1.000",
              "sodium": "21",
              "sugar": "0.07",
              "vitamin_a": "0",
              "vitamin_c": "1"
            },
            {
              "calcium": "4",
              "calories": "235",
              "carbohydrate": "9.44",
              "cholesterol": "68",
              "fat": "10.87",
              "fiber": "0.3",
              "iron": "5",
              "measurement_description": "cup, cooked, flaked",
              "metric_serving_amount": "136.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "4.736",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "3.037",
              "potassium": "521",
              "protein": "23.70",
              "saturated_fat": "2.267",
              "serving_description": "1 cup flaked",
              "serving_id": "7065",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/cod-battered-fried?portionid=7065&portionamount=1.000",
              "sodium": "170",
              "sugar": "0.57",
              "vitamin_a": "1",
              "vitamin_c": "5"
            },
            {
              "calcium": "2",
              "calories": "147",
              "carbohydrate": "5.90",
              "cholesterol": "43",
              "fat": "6.79",
              "fiber": "0.2",
              "iron": "3",
              "measurement_description": "serving (85g)",
              "metric_serving_amount": "85.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "2.960",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "1.898",
              "potassium": "326",
              "protein": "14.82",
              "saturated_fat": "1.417",
              "serving_description": "1 serving (85 g)",
              "serving_id": "7628",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/cod-battered-fried?portionid=7628&portionamount=1.000",
              "sodium": "106",
              "sugar": "0.36",
              "vitamin_a": "0",
              "vitamin_c": "3"
            },
            {
              "calcium": "3",
              "calories": "190",
              "carbohydrate": "7.63",
              "cholesterol": "55",
              "fat": "8.79",
              "fiber": "0.2",
              "iron": "4",
              "measurement_description": "Pacific cod fillet (6-1/4\" x 3\" x 3/8\")",
              "metric_serving_amount": "110.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "3.831",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "2.456",
              "potassium": "421",
              "protein": "19.17",
              "saturated_fat": "1.834",
              "serving_description": "1 Pacific cod fillet (6-1/4\" x 3\" x 3/8\")",
              "serving_id": "7337",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/cod-battered-fried?portionid=7337&portionamount=1.000",
              "sodium": "138",
              "sugar": "0.46",
              "vitamin_a": "1",
              "vitamin_c": "4"
            },
            {
              "calcium": "3",
              "calories": "173",
              "carbohydrate": "6.94",
              "cholesterol": "50",
              "fat": "7.99",
              "fiber": "0.2",
              "iron": "4",
              "measurement_description": "g",
              "metric_serving_amount": "100.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "3.483",
              "number_of_units": "100.000",
              "polyunsaturated_fat": "2.233",
              "potassium": "383",
              "protein": "17.43",
              "saturated_fat": "1.667",
              "serving_description": "100 g",
              "serving_id": "50652",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/cod-battered-fried?portionid=50652&portionamount=100.000",
              "sodium": "125",
              "sugar": "0.42",
              "vitamin_a": "1",
              "vitamin_c": "3"
            }
          ]
        }
      }
    },
    {
      "food": {
        "food_id": "5765",
        "food_name": "Deep Fried Potato French Fries",
        "food_type": "Generic",
        "food_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried",
        "servings": {
          "serving": [
            {
              "calcium": "0",
              "calories": "112",
              "carbohydrate": "13.14",
              "cholesterol": "0",
              "fat": "5.96",
              "fiber": "1.2",
              "iron": "3",
              "measurement_description": "10 strips (1\" to 2\")",
              "metric_serving_amount": "35.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "3.447",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "1.034",
              "potassium": "194",
              "protein": "1.32",
              "saturated_fat": "1.412",
              "serving_description": "1 10 strip portion (1\" to 2\")",
              "serving_id": "19956",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=19956&portionamount=1.000",
              "sodium": "68",
              "sugar": "0.24",
              "vitamin_a": "0",
              "vitamin_c": "2"
            },
            {
              "calcium": "1",
              "calories": "160",
              "carbohydrate": "18.76",
              "cholesterol": "0",
              "fat": "8.52",
              "fiber": "1.8",
              "iron": "4",
              "measurement_description": "10 strips (2\" to 3-1/2\")",
              "metric_serving_amount": "50.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "4.924",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "1.478",
              "potassium": "276",
              "protein": "1.88",
              "saturated_fat": "2.017",
              "serving_description": "1 10 strip portion (2\" to 3-1/2\")",
              "serving_id": "20827",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=20827&portionamount=1.000",
              "sodium": "96",
              "sugar": "0.34",
              "vitamin_a": "0",
              "vitamin_c": "2"
            },
            {
              "calcium": "1",
              "calories": "249",
              "carbohydrate": "29.27",
              "cholesterol": "0",
              "fat": "13.28",
              "fiber": "2.7",
              "iron": "6",
              "measurement_description": "10 strips (3-1/2\" to 4\")",
              "metric_serving_amount": "78.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "7.681",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "2.305",
              "potassium": "431",
              "protein": "2.93",
              "saturated_fat": "3.147",
              "serving_description": "1 10 strip portion (3-1/2\" to 4\")",
              "serving_id": "20859",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=20859&portionamount=1.000",
              "sodium": "151",
              "sugar": "0.53",
              "vitamin_a": "0",
              "vitamin_c": "4"
            },
            {
              "calcium": "0",
              "calories": "61",
              "carbohydrate": "7.13",
              "cholesterol": "0",
              "fat": "3.24",
              "fiber": "0.7",
              "iron": "1",
              "measurement_description": "10 shoestrings",
              "metric_serving_amount": "19.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.871",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.561",
              "potassium": "105",
              "protein": "0.71",
              "saturated_fat": "0.766",
              "serving_description": "1 10 shoestrings serving",
              "serving_id": "21281",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=21281&portionamount=1.000",
              "sodium": "37",
              "sugar": "0.13",
              "vitamin_a": "0",
              "vitamin_c": "1"
            },
            {
              "calcium": "1",
              "calories": "134",
              "carbohydrate": "15.76",
              "cholesterol": "0",
              "fat": "7.15",
              "fiber": "1.5",
              "iron": "3",
              "measurement_description": "10 straight cuts",
              "metric_serving_amount": "42.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "4.136",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "1.241",
              "potassium": "232",
              "protein": "1.58",
              "saturated_fat": "1.694",
              "serving_description": "1 10 straight cuts serving",
              "serving_id": "21596",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=21596&portionamount=1.000",
              "sodium": "81",
              "sugar": "0.29",
              "vitamin_a": "0",
              "vitamin_c": "2"
            },
            {
              "calcium": "1",
              "calories": "169",
              "carbohydrate": "19.89",
              "cholesterol": "0",
              "fat": "9.03",
              "fiber": "1.9",
              "iron": "4",
              "measurement_description": "10 crinkle cuts",
              "metric_serving_amount": "53.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "5.219",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "1.566",
              "potassium": "293",
              "protein": "1.99",
              "saturated_fat": "2.138",
              "serving_description": "1 10 crinkle cuts serving",
              "serving_id": "20883",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=20883&portionamount=1.000",
              "sodium": "102",
              "sugar": "0.36",
              "vitamin_a": "0",
              "vitamin_c": "2"
            },
            {
              "calcium": "1",
              "calories": "182",
              "carbohydrate": "21.39",
              "cholesterol": "0",
              "fat": "9.71",
              "fiber": "2.0",
              "iron": "4",
              "measurement_description": "cup",
              "metric_serving_amount": "57.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "5.613",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "1.684",
              "potassium": "315",
              "protein": "2.14",
              "saturated_fat": "2.299",
              "serving_description": "1 cup",
              "serving_id": "20945",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=20945&portionamount=1.000",
              "sodium": "110",
              "sugar": "0.39",
              "vitamin_a": "0",
              "vitamin_c": "3"
            },
            {
              "calcium": "2",
              "calories": "427",
              "carbohydrate": "50.29",
              "cholesterol": "0",
              "fat": "22.82",
              "fiber": "4.7",
              "iron": "10",
              "measurement_description": "fast food order",
              "metric_serving_amount": "134.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "13.196",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "3.960",
              "potassium": "741",
              "protein": "5.04",
              "saturated_fat": "5.406",
              "serving_description": "1 fast food order",
              "serving_id": "21007",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=21007&portionamount=1.000",
              "sodium": "259",
              "sugar": "0.91",
              "vitamin_a": "0",
              "vitamin_c": "6"
            },
            {
              "calcium": "0",
              "calories": "41",
              "carbohydrate": "4.88",
              "cholesterol": "0",
              "fat": "2.21",
              "fiber": "0.5",
              "iron": "1",
              "measurement_description": "oz, raw, yields",
              "metric_serving_amount": "13.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "1.280",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "0.384",
              "potassium": "72",
              "protein": "0.49",
              "saturated_fat": "0.524",
              "serving_description": "1 oz, raw, yields",
              "serving_id": "21829",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=21829&portionamount=1.000",
              "sodium": "25",
              "sugar": "0.09",
              "vitamin_a": "0",
              "vitamin_c": "1"
            },
            {
              "calcium": "3",
              "calories": "622",
              "carbohydrate": "73.18",
              "cholesterol": "0",
              "fat": "33.21",
              "fiber": "6.8",
              "iron": "15",
              "measurement_description": "\"super\" fast food order",
              "metric_serving_amount": "195.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "19.204",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "5.762",
              "potassium": "1078",
              "protein": "7.33",
              "saturated_fat": "7.866",
              "serving_description": "1 \"super\" fast food order",
              "serving_id": "20773",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=20773&portionamount=1.000",
              "sodium": "376",
              "sugar": "1.33",
              "vitamin_a": "0",
              "vitamin_c": "9"
            },
            {
              "calcium": "2",
              "calories": "539",
              "carbohydrate": "63.43",
              "cholesterol": "0",
              "fat": "28.78",
              "fiber": "5.9",
              "iron": "13",
              "measurement_description": "large fast food order",
              "metric_serving_amount": "169.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "16.643",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "4.994",
              "potassium": "935",
              "protein": "6.35",
              "saturated_fat": "6.817",
              "serving_description": "1 large fast food order",
              "serving_id": "19957",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=19957&portionamount=1.000",
              "sodium": "326",
              "sugar": "1.15",
              "vitamin_a": "0",
              "vitamin_c": "8"
            },
            {
              "calcium": "1",
              "calories": "281",
              "carbohydrate": "33.03",
              "cholesterol": "0",
              "fat": "14.99",
              "fiber": "3.1",
              "iron": "7",
              "measurement_description": "10 steak cut/dinner fries",
              "metric_serving_amount": "88.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "8.666",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "2.600",
              "potassium": "487",
              "protein": "3.31",
              "saturated_fat": "3.550",
              "serving_description": "1 10 steak cut/dinner fries serving",
              "serving_id": "20681",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=20681&portionamount=1.000",
              "sodium": "170",
              "sugar": "0.60",
              "vitamin_a": "0",
              "vitamin_c": "4"
            },
            {
              "calcium": "1",
              "calories": "281",
              "carbohydrate": "33.03",
              "cholesterol": "0",
              "fat": "14.99",
              "fiber": "3.1",
              "iron": "7",
              "measurement_description": "10 wedges",
              "metric_serving_amount": "88.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "8.666",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "2.600",
              "potassium": "487",
              "protein": "3.31",
              "saturated_fat": "3.550",
              "serving_description": "1 10 wedges serving",
              "serving_id": "20884",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=20884&portionamount=1.000",
              "sodium": "170",
              "sugar": "0.60",
              "vitamin_a": "0",
              "vitamin_c": "4"
            },
            {
              "calcium": "1",
              "calories": "160",
              "carbohydrate": "18.76",
              "cholesterol": "0",
              "fat": "8.52",
              "fiber": "1.8",
              "iron": "4",
              "measurement_description": "10 strips, NFS",
              "metric_serving_amount": "50.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "4.924",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "1.478",
              "potassium": "276",
              "protein": "1.88",
              "saturated_fat": "2.017",
              "serving_description": "1 10 strip serving, NFS",
              "serving_id": "21401",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=21401&portionamount=1.000",
              "sodium": "96",
              "sugar": "0.34",
              "vitamin_a": "0",
              "vitamin_c": "2"
            },
            {
              "calcium": "1",
              "calories": "223",
              "carbohydrate": "26.27",
              "cholesterol": "0",
              "fat": "11.92",
              "fiber": "2.4",
              "iron": "5",
              "measurement_description": "serving (70g)",
              "metric_serving_amount": "70.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "6.894",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "2.068",
              "potassium": "387",
              "protein": "2.63",
              "saturated_fat": "2.824",
              "serving_description": "1 serving (70 g)",
              "serving_id": "21781",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=21781&portionamount=1.000",
              "sodium": "135",
              "sugar": "0.48",
              "vitamin_a": "0",
              "vitamin_c": "3"
            },
            {
              "calcium": "1",
              "calories": "258",
              "carbohydrate": "30.40",
              "cholesterol": "0",
              "fat": "13.79",
              "fiber": "2.8",
              "iron": "6",
              "measurement_description": "10 spirals, twists, curly fries",
              "metric_serving_amount": "81.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "7.977",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "2.394",
              "potassium": "448",
              "protein": "3.05",
              "saturated_fat": "3.268",
              "serving_description": "1 10 spirals, twists, curly fries serving",
              "serving_id": "21015",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=21015&portionamount=1.000",
              "sodium": "156",
              "sugar": "0.55",
              "vitamin_a": "0",
              "vitamin_c": "4"
            },
            {
              "calcium": "1",
              "calories": "271",
              "carbohydrate": "31.90",
              "cholesterol": "0",
              "fat": "14.48",
              "fiber": "3.0",
              "iron": "6",
              "measurement_description": "small fast food order",
              "metric_serving_amount": "85.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "8.371",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "2.512",
              "potassium": "470",
              "protein": "3.20",
              "saturated_fat": "3.429",
              "serving_description": "1 small fast food order",
              "serving_id": "20684",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=20684&portionamount=1.000",
              "sodium": "164",
              "sugar": "0.58",
              "vitamin_a": "0",
              "vitamin_c": "4"
            },
            {
              "calcium": "2",
              "calories": "427",
              "carbohydrate": "50.29",
              "cholesterol": "0",
              "fat": "22.82",
              "fiber": "4.7",
              "iron": "10",
              "measurement_description": "medium fast food order",
              "metric_serving_amount": "134.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "13.196",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "3.960",
              "potassium": "741",
              "protein": "5.04",
              "saturated_fat": "5.406",
              "serving_description": "1 medium fast food order",
              "serving_id": "21169",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=21169&portionamount=1.000",
              "sodium": "259",
              "sugar": "0.91",
              "vitamin_a": "0",
              "vitamin_c": "6"
            },
            {
              "calcium": "1",
              "calories": "258",
              "carbohydrate": "30.40",
              "cholesterol": "0",
              "fat": "13.79",
              "fiber": "2.8",
              "iron": "6",
              "measurement_description": "cup, curly fries",
              "metric_serving_amount": "81.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "7.977",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "2.394",
              "potassium": "448",
              "protein": "3.05",
              "saturated_fat": "3.268",
              "serving_description": "1 cup curly fries",
              "serving_id": "20761",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=20761&portionamount=1.000",
              "sodium": "156",
              "sugar": "0.55",
              "vitamin_a": "0",
              "vitamin_c": "4"
            },
            {
              "calcium": "1",
              "calories": "262",
              "carbohydrate": "30.77",
              "cholesterol": "0",
              "fat": "13.96",
              "fiber": "2.9",
              "iron": "6",
              "measurement_description": "10 waffle fries",
              "metric_serving_amount": "82.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "8.075",
              "number_of_units": "1.000",
              "polyunsaturated_fat": "2.423",
              "potassium": "453",
              "protein": "3.08",
              "saturated_fat": "3.308",
              "serving_description": "1 10 waffle fries serving",
              "serving_id": "21830",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=21830&portionamount=1.000",
              "sodium": "158",
              "sugar": "0.56",
              "vitamin_a": "0",
              "vitamin_c": "4"
            },
            {
              "calcium": "1",
              "calories": "319",
              "carbohydrate": "37.53",
              "cholesterol": "0",
              "fat": "17.03",
              "fiber": "3.5",
              "iron": "8",
              "measurement_description": "g",
              "metric_serving_amount": "100.000",
              "metric_serving_unit": "g",
              "monounsaturated_fat": "9.848",
              "number_of_units": "100.000",
              "polyunsaturated_fat": "2.955",
              "potassium": "553",
              "protein": "3.76",
              "saturated_fat": "4.034",
              "serving_description": "100 g",
              "serving_id": "54445",
              "serving_url": "https://www.fatsecret.com/calories-nutrition/generic/white-potato-french-fries-from-frozen-deep-fried?portionid=54445&portionamount=100.000",
              "sodium": "193",
              "sugar": "0.68",
              "vitamin_a": "0",
              "vitamin_c": "5"
            }
          ]
        }
      }
    },
    {
      "food": {
        "brand_name": "Goose Island",
        "food_id": "500175",
        "food_name": "IPA Beer",
        "food_type": "Brand",
        "food_url": "https://www.fatsecret.com/calories-nutrition/goose-island/ipa-beer",
        "servings": {
          "serving": {
            "calcium": "0",
            "calories": "206",
            "carbohydrate": "21.5",
            "cholesterol": "0",
            "fat": "0",
            "fiber": "0",
            "iron": "0",
            "measurement_description": "serving",
            "metric_serving_amount": "12.000",
            "metric_serving_unit": "oz",
            "monounsaturated_fat": "0",
            "number_of_units": "1.000",
            "polyunsaturated_fat": "0",
            "potassium": "0",
            "protein": "0",
            "saturated_fat": "0",
            "serving_description": "1 bottle",
            "serving_id": "526347",
            "serving_url": "https://www.fatsecret.com/calories-nutrition/goose-island/ipa-beer",
            "sodium": "0",
            "sugar": "0",
            "trans_fat": "0",
            "vitamin_a": "0",
            "vitamin_c": "0"
          }
        }
      }
    }
  ]

  export default topTenFoodsList;